library(readxl)
library(moments)
rm(list = ls())
my_data <- read_xlsx("C:\\Users\\Gabriel\\OneDrive - usp.br\\Área de Trabalho\\7°Semestre\\IntroQualidade\\Dados dos alunos_1.xlsx", sheet = "Turma 03A") #nolint

class(my_data)
str(my_data)
head(my_data)
names(my_data)
# my_data <- read_xls()("C:\\Users\\Gabriel\\OneDrive - usp.br\\Área de Trabalho\\7°Semestre\\IntroQualidade\\Dados dos alunos.csv", header=TRUE) #nolint
# my_data <- na.omit(my_data)

# print(my_data)
# print(is.na(my_data))
#my_data_1 <- data.frame(my_data$Idade, my_data$Altura, my_data$Peso)
max_idade <- max(na.omit(my_data)$Idade)
min_idade <- min(na.omit(my_data)$Idade)
max_altura <- max(na.omit(my_data)$Altura)
min_altura <- min(na.omit(my_data)$Altura)
max_peso <- max(na.omit(my_data)$Peso)
min_peso <- min(na.omit(my_data)$Peso)
print(max_idade)
print(min_idade)
print(max_altura)
print(min_altura)
print(max_peso)
print(min_peso)

mean_idade <- mean(na.omit(my_data)$Idade)
mean_altura <- mean(na.omit(my_data)$Altura)
mean_peso <- mean(na.omit(my_data)$Peso)
print(mean_idade)
print(mean_altura)
print(mean_peso)